name: dev-build
permissions:
  id-token: write # Required for requesting the JWT 
  contents: read  # Required for checkout
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.2.2
        with:
          url: ${{ vars.CONJUR_URL }}
          account: ${{ vars.CONJUR_ACCOUNT }}
          authn_id: ${{ vars.CONJUR_AUTHN_ID }}
          secrets: data/vault/dev-reporting-app/dev-reporting-app-db-credentials_postgresql_aws/username|SECRET1;data/vault/dev-reporting-app/dev-reporting-app-db-credentials_postgresql_aws/password|SECRET2

      - name: Echo USERNAME
        run: echo $SECRET1 | sed 's/./& /g'

      - name: Echo PASSWORD
        run: echo $SECRET2 | sed 's/./& /g'

      - name: Debug JWT
        run: |
          echo "Authenticate via Authn-JWT"
          JWT_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)

          # Extract 2nd section (payload), convert base64url chars, decode, and format JSON
          echo "$JWT_TOKEN" | cut -d'.' -f2 | tr '_-' '/+' | base64 -d 2>/dev/null | jq .
